-- Dedicated intermediate stops for each planned trip day.
create table if not exists public.trip_day_waypoints (
  id bigint generated by default as identity primary key,
  trip_day_id uuid not null references public.trip_days(id) on delete cascade,
  name text not null,
  display_order integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists trip_day_waypoints_trip_day_id_idx
  on public.trip_day_waypoints (trip_day_id, display_order);

alter table public.trip_day_waypoints enable row level security;

drop policy if exists "trip_day_waypoints_select" on public.trip_day_waypoints;
drop policy if exists "trip_day_waypoints_insert" on public.trip_day_waypoints;
drop policy if exists "trip_day_waypoints_update" on public.trip_day_waypoints;
drop policy if exists "trip_day_waypoints_delete" on public.trip_day_waypoints;

create policy "trip_day_waypoints_select" on public.trip_day_waypoints for select using (true);
create policy "trip_day_waypoints_insert" on public.trip_day_waypoints for insert with check (true);
create policy "trip_day_waypoints_update" on public.trip_day_waypoints for update using (true) with check (true);
create policy "trip_day_waypoints_delete" on public.trip_day_waypoints for delete using (true);

-- One-time migration of legacy waypoints stored inside trip_days.notes.
do $$
declare
  r record;
  waypoint text;
  clean_notes text;
begin
  for r in
    select id, notes
    from public.trip_days
    where notes like '%[[WAYPOINTS:%'
  loop
    begin
      for waypoint in
        select jsonb_array_elements_text(
          substring(r.notes from '\[\[WAYPOINTS:(\[.*?\])\]\]')::jsonb
        )
      loop
        if btrim(waypoint) <> '' and not exists (
          select 1 from public.trip_day_waypoints w
          where w.trip_day_id = r.id and lower(w.name) = lower(btrim(waypoint))
        ) then
          insert into public.trip_day_waypoints (trip_day_id, name, display_order)
          values (
            r.id,
            btrim(waypoint),
            coalesce((select max(display_order) + 1 from public.trip_day_waypoints where trip_day_id = r.id), 1)
          );
        end if;
      end loop;

      clean_notes := btrim(regexp_replace(r.notes, '\[\[WAYPOINTS:\[.*?\]\]\][[:space:]]*', '', 'g'));
      update public.trip_days set notes = nullif(clean_notes, '') where id = r.id;
    exception when others then
      raise notice 'Legacy waypoint migration skipped for trip_day %: %', r.id, sqlerrm;
    end;
  end loop;
end $$;
